Atlanta Hawks: https://docs.google.com/spreadsheets/d/1PFzYgqawj4UAmeKpVMyVdw0jQsu0bEwqNgLUzs5jgoY
Boston Celtics: https://docs.google.com/spreadsheets/d/1kqBJaGa44YmPNxawNqWT0garIjqzvRR0qyqrhte53oA
Brooklyn Nets: https://docs.google.com/spreadsheets/d/1Emc_u7H67gtaoE40soSyJZhLdmv_usGcJo-iDis-yP8
Charlotte Hornets: https://docs.google.com/spreadsheets/d/1A2L6KuIbN-6QMxtOCpWTgjms5PkQ8bJtQEeCwOITcIE
Chicago Bulls: https://docs.google.com/spreadsheets/d/1A-szRAELLENPcA-RUdLbZsGmHOdaYzLQMfhbsMvEuQY
Cleveland Cavaliers: https://docs.google.com/spreadsheets/d/1scEptvH2_ElqsT8M8jG1wZYSIpgsI6v0wcmwvQdr4S8
Dallas Mavericks: https://docs.google.com/spreadsheets/d/107lQUpSytevmf93o0C45saU42lKItxGwt1o0iu9G8a8
Denver Nuggets: https://docs.google.com/spreadsheets/d/1_tCerQamHIq0SZ7-ANvCP2YhiuLugj0pJ1mAk7RIbr8
Detroit Pistons: https://docs.google.com/spreadsheets/d/1jxa1LtlDbgYGByh9SRdL9eEEiDMjlYuDSLO6geQdqCk
Golden State Warriors: https://docs.google.com/spreadsheets/d/1Z1XNlxnmH5VWdvZ6glxvnNOXswlnqami1Au9jyzZiBM
Houston Rockets: https://docs.google.com/spreadsheets/d/1M9_KuX6vXruQ-k9o2NbknmU8VmFvxS5WsA8xVQ9kSOQ
Indiana Pacers: https://docs.google.com/spreadsheets/d/1UdG7m6MOn3hqdNQzp9LBQI0v4sY_picp4kEAlw4sIWY
Los Angeles Clippers: https://docs.google.com/spreadsheets/d/10dg3xeeCFsqcDJXUVk30JveNGAgHI3ubvW3Jgu6CUAE
Los Angeles Lakers: https://docs.google.com/spreadsheets/d/1IMCO7zq91KM5DLnzKauS7fevO5N7OcZStoOklsU7nDo
Memphis Grizzlies: https://docs.google.com/spreadsheets/d/1aMHzE-tnvuF3RaQU64hrcQ8IELgkziih9Y2A1eWbc7s
Miami Heat: https://docs.google.com/spreadsheets/d/11itQtW5Pg-H_KYa4UXmfOk7_A9WTDW0JtugSHUc6iT8
Milwaukee Bucks: https://docs.google.com/spreadsheets/d/1Vl8RTaVlqRZg8oBcaTwnW2H-xg1rDUIDuPqOtoJPHHs
Minnesota Timberwolves: https://docs.google.com/spreadsheets/d/1Ctb7shrDZxwJZleUX1bLj3ChOqTyxrDCcDnGXQYtx3c
New Orleans Pelicans: https://docs.google.com/spreadsheets/d/1CAE45QZhkcuCJYzYzaoViht0JnYPFEQYlFdUgNbQHag
New York Knicks: https://docs.google.com/spreadsheets/d/1cLYP-Jtvr3Ux_iElXyhCtsrWIuYdcgQnqYR1kCc-lak
Oklahoma City Thunder: https://docs.google.com/spreadsheets/d/1Vwv_nlYhtti_E7B95s3E60nMOvC0H54Za-eRYJeEUcY
Orlando Magic: https://docs.google.com/spreadsheets/d/1scR_-nTv7Jq61HcnIpisUFEwxllrnhQyro-eKFxZZEA
Philadelphia 76ers: https://docs.google.com/spreadsheets/d/1JSM8c9WM2w6dKd5af9HqpfqWZ0jBAbx_LX6IkBY7Two
Phoenix Suns: https://docs.google.com/spreadsheets/d/1ufFs3RIxAoH92FRkCK7OzEYD8hJ4VAAXqX04VZDcXWU
Portland Trail Blazers: https://docs.google.com/spreadsheets/d/1ucikYbpYcZo6G15881OapBnWXNgCdsxrPXKEJvVj5L0
Sacramento Kings: https://docs.google.com/spreadsheets/d/1WiFkcGnHpWHWxeBA-uRpCdJD1z4cutl24oSYspEaHRw
San Antonio Spurs: https://docs.google.com/spreadsheets/d/1cZoM-1dqaBaXb57TxtXrTquyv6Clr3s-5dEHGTsTV18
Toronto Raptors: https://docs.google.com/spreadsheets/d/1ESxRj2mWQp6_N-GpkigLVcyzitOc7f7pNl8SlDc8P8s
Utah Jazz: https://docs.google.com/spreadsheets/d/1bEpZjnBppchM6KyPbBIglR5JwC7KPmabDDMkrn_eB2k
Washington Wizards: https://docs.google.com/spreadsheets/d/1sA0i5QIJJN6NCWmsSj2NAFcyTe5gfXjSapLofVmP-y8
